version: '3.8'

services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prettygood
      POSTGRES_TEST_DB: "true"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/prettygood
      PGRST_DB_SCHEMA: prettygood
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: "your-jwt-secret-here-change-in-production"
      PGRST_DB_POOL: 10
      PGRST_SERVER_PROXY_URI: "http://localhost:3000"
    depends_on:
      postgres:
        condition: service_healthy

  # Alternative to pg_prove for running tests with a nice UI
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prettygood.music
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
